In [61]:
import requests
import csv
import pandas as pd
import io

http_proxy="http://10.144.1.10:8080"
https_proxy="http://10.144.1.10:8080"
proxyDict={
    "http": http_proxy,
    "https": https_proxy
}

In [114]:
list_ =[]
frame = pd.DataFrame()
def getdataframes(frame):
    firms = {"NDAQ","^SP500TR","BK","BFED","BLK","CARV","C","CME","EVR","FII","FIG","GBL","LAZ","NTRS","BPOP","PFS","STT","BX","BX"}
    returns = pd.DataFrame()
    for x in firms:
        request = 'http://chart.finance.yahoo.com/table.csv?s={}&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv'.format(str(x))
        print (request)
        x = pd.read_csv(io.StringIO(requests.get(request,proxies=proxyDict).content.decode('utf-8')))
        list_.append(x)
        #x = pd.DataFrame.from_csv(request)
        #x=pd.DataFrame(cr)
        #my_list = list(cr)
        #x = pd.DataFrame(data=my_list)
        #returns=pd.concat(x, axis=1,ignore_index=True)
        print (x)
    frame=pd.concat(list_,axis=1)
    return frame
    #print(frame)

In [115]:
returns = getdataframes(frame)
returns

http://chart.finance.yahoo.com/table.csv?s=STT&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close   Volume  Adj Close
0   2008-12-10  42.349998  43.590000  40.700001  41.759998  4085900  37.144048
1   2008-12-09  43.200001  45.650002  41.360001  41.799999  6530100  37.179628
2   2008-12-08  41.490002  44.419998  41.040001  43.869999  5589700  39.020820
3   2008-12-05  36.220001  40.389999  35.250000  40.279999  6371500  35.827641
4   2008-12-04  36.549999  40.389999  35.880001  37.320000  5448000  33.194826
5   2008-12-03  36.619999  36.930000  34.799999  36.599998  6007600  32.554410
6   2008-12-02  35.880001  37.259998  34.110001  36.930000  4675000  32.847935
7   2008-12-01  40.380001  41.000000  35.180000  35.430000  5858900  31.513738
8   2008-11-28  40.650002  42.500000  39.900002  42.110001  1833800  37.455363
9   2008-11-26  35.700001  40.799999  35.250000  40.650002  5778200  36.156745
10  2008-11-25  38.290001  38.740002  35.669998  37.750000  6608200  33.577296
11  2008-11-24  33.680000  36.900002  32.029999  36.090000  7017300  32.100785
12  2008-11-21  29.809999  32.080002  28.240000  31.780001  8064700  28.267192
http://chart.finance.yahoo.com/table.csv?s=PFS&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date   Open   High    Low  Close   Volume  Adj Close
0   2008-12-10  14.50  14.65  13.75  14.11   649600  10.591806
1   2008-12-09  14.37  15.29  14.34  14.58   532700  10.944617
2   2008-12-08  14.62  14.96  14.24  14.68   513300  11.019683
3   2008-12-05  13.32  14.24  12.70  14.24   692900  10.689392
4   2008-12-04  13.99  14.07  13.20  13.49   606000  10.126398
5   2008-12-03  13.41  14.34  13.21  13.99   652900  10.501727
6   2008-12-02  12.69  13.62  12.65  13.60   637100  10.208971
7   2008-12-01  14.47  14.84  12.58  12.60   833400   9.458311
8   2008-11-28  14.80  15.11  14.64  14.99   270400  11.252387
9   2008-11-26  14.26  14.96  14.26  14.96   906700  11.229867
10  2008-11-25  15.33  15.33  14.23  14.76   722000  11.079736
11  2008-11-24  14.13  15.73  13.33  15.08   991600  11.319946
12  2008-11-21  13.42  13.48  12.00  13.36  1063100  10.028812
http://chart.finance.yahoo.com/table.csv?s=BX&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date  Open  High   Low  Close   Volume  Adj Close
0   2008-12-10  7.16  7.28  6.56   6.59  1700500   4.197238
1   2008-12-09  6.42  7.34  6.26   7.01  1799100   4.464740
2   2008-12-08  6.46  7.00  6.32   6.89  1818300   4.388311
3   2008-12-05  5.68  6.30  5.50   6.27  1308100   3.993427
4   2008-12-04  5.83  6.12  5.57   5.73  1133400   3.649495
5   2008-12-03  5.34  6.28  5.18   6.04  1910600   3.846937
6   2008-12-02  5.60  5.83  5.18   5.34  1814600   3.401100
7   2008-12-01  6.00  6.07  5.50   5.56   947700   3.541220
8   2008-11-28  6.32  6.33  5.70   6.26   738700   3.987058
9   2008-11-26  5.63  6.30  5.61   6.29  1317500   4.006165
10  2008-11-25  6.25  6.29  5.58   6.14  1701400   3.910628
11  2008-11-24  4.90  6.47  4.66   6.43  2833400   3.904259
12  2008-11-21  5.41  5.45  4.15   4.65  2591800   2.823453
http://chart.finance.yahoo.com/table.csv?s=BK&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close    Volume  \
0   2008-12-10  28.719999  29.080000  27.570000  28.709999   7575300
1   2008-12-09  29.940001  30.180000  27.000000  27.629999  15138300
2   2008-12-08  31.629999  31.629999  28.610001  30.750000  12929500
3   2008-12-05  28.309999  30.360001  27.760000  30.120001  10922700
4   2008-12-04  28.889999  30.360001  27.530001  28.540001  11438000
5   2008-12-03  26.340000  30.049999  26.100000  29.590000  11564500
6   2008-12-02  25.820000  27.540001  25.260000  27.139999  10532700
7   2008-12-01  29.219999  29.969999  25.080000  25.850000  12104200
8   2008-11-28  29.879999  31.120001  28.799999  30.209999   6050200
9   2008-11-26  28.860001  30.030001  28.660000  29.959999   9972400
10  2008-11-25  32.380001  32.650002  28.360001  29.750000  14562100
11  2008-11-24  26.850000  32.430000  25.840000  32.250000  17266100
12  2008-11-21  25.150000  26.240000  23.000000  25.840000  18598300

    Adj Close
0   24.684703
1   23.756125
2   26.438684
3   25.897015
4   24.538539
5   25.441323
6   23.334825
7   22.225691
8   25.974395
9   25.759446
10  25.578890
11  27.728376
12  22.217093
http://chart.finance.yahoo.com/table.csv?s=LAZ&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close   Volume  Adj Close
0   2008-12-10  28.690001  30.150000  27.969999  29.490000  1229300  22.687298
1   2008-12-09  28.709999  29.930000  27.660000  28.760000   874300  22.125693
2   2008-12-08  26.459999  29.400000  26.299999  29.219999   835300  22.479581
3   2008-12-05  24.879999  25.740000  23.969999  25.530001  1346000  19.640785
4   2008-12-04  25.639999  27.090000  24.940001  25.100000   887400  19.309976
5   2008-12-03  24.320000  26.430000  24.320000  26.180000  1240800  20.140843
6   2008-12-02  25.950001  26.520000  23.730000  25.389999   956200  19.533079
7   2008-12-01  29.790001  30.150000  25.370001  25.440001  1090500  19.571545
8   2008-11-28  29.350000  31.270000  28.980000  31.260000   704200  24.048998
9   2008-11-26  25.719999  30.129999  24.900000  30.010000   865200  23.087346
10  2008-11-25  26.129999  27.040001  24.080000  26.190001  1224900  20.148537
11  2008-11-24  23.430000  26.059999  23.430000  25.940001  1138800  19.956206
12  2008-11-21  21.100000  23.000000  19.990000  22.870001  1771500  17.594389
http://chart.finance.yahoo.com/table.csv?s=CME&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date        Open        High         Low       Close    Volume  \
0   2008-12-10  223.840008  229.489994  214.020004  221.369991   5718000
1   2008-12-09  218.509998  238.549995  215.529995  217.900009  10097000
2   2008-12-08  206.000004  228.649998  206.000004  223.290005  10723000
3   2008-12-05  174.009991  196.690006  172.299995  194.570007   7553500
4   2008-12-04  177.520008  191.900005  174.319992  177.460003   6941000
5   2008-12-03  166.000004  183.169994  162.999992  182.290001   7315500
6   2008-12-02  171.289997  178.509998  156.020002  172.600002  12620500
7   2008-12-01  197.010002  197.999992  172.630005  172.639999   7584500
8   2008-11-28  205.000000  211.949997  201.910000  211.949997   2481000
9   2008-11-26  193.129997  214.860001  190.480003  211.760006   5227000
10  2008-11-25  205.699997  212.500000  190.000000  199.939995   7209500
11  2008-11-24  181.480007  201.110001  171.849995  200.709991  11333000
12  2008-11-21  164.039993  176.879997  162.000008  175.779991  13227500

    Adj Close
0   32.886330
1   32.370836
2   33.171564
3   28.734130
4   26.207322
5   26.920617
6   25.489597
7   25.495503
8   31.300810
9   31.272752
10  29.527171
11  29.640884
12  25.959218
http://chart.finance.yahoo.com/table.csv?s=FII&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close   Volume  Adj Close
0   2008-12-10  22.600000  23.340000  22.469999  23.209999  1255000  15.243887
1   2008-12-09  22.010000  23.549999  21.850000  22.580000  1927800  14.830115
2   2008-12-08  22.389999  22.969999  21.900000  22.420000  1469600  14.725030
3   2008-12-05  19.570000  21.370001  18.860001  21.370001  1265000  14.035411
4   2008-12-04  19.969999  21.190001  18.950001  19.440001  1580900  12.767823
5   2008-12-03  18.690001  20.530001  18.500000  20.500000  1278800  13.464011
6   2008-12-02  18.170000  19.910000  17.900000  19.469999  1578000  12.787526
7   2008-12-01  18.990000  19.469999  17.750000  17.770000  1898900  11.670999
8   2008-11-28  19.150000  19.850000  18.870001  19.850000   656100  13.037103
9   2008-11-26  17.820000  19.309999  17.480000  19.010000  1401300  12.485407
10  2008-11-25  18.180000  18.780001  16.799999  18.350000  1804200  12.051932
11  2008-11-24  18.260000  19.209999  17.879999  18.930000  2242600  12.432865
12  2008-11-21  17.520000  17.860001  15.900000  17.610001  2025500  11.565914
http://chart.finance.yahoo.com/table.csv?s=CARV&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date      Open      High       Low     Close  Volume  Adj Close
0   2008-12-10  5.700285  6.450323  5.700285  6.450323       0  88.121687
1   2008-12-09  5.040252  6.270314  4.900245  5.600280     700  76.508751
2   2008-12-08  5.260263  5.600280  5.260263  5.600280       0  76.508751
3   2008-12-05  5.600280  5.600280  5.600280  5.600280       0  76.508751
4   2008-12-04  5.600280  5.970299  5.600280  5.600280       0  76.508751
5   2008-12-03  5.610281  5.610281  5.600280  5.600280     200  76.508751
6   2008-12-02  5.500275  5.600280  5.500275  5.600280     100  76.508751
7   2008-12-01  5.600280  5.600280  5.600280  5.600280       0  76.508751
8   2008-11-28  5.600280  5.600280  5.600280  5.600280       0  76.508751
9   2008-11-26  5.510276  5.610281  5.510276  5.600280     100  76.508751
10  2008-11-25  5.790289  5.950298  5.750288  5.950298     100  81.290548
11  2008-11-24  6.500325  6.510326  5.750288  6.490324     800  87.301947
12  2008-11-21  6.500325  6.500325  6.500325  6.500325     100  87.436466
http://chart.finance.yahoo.com/table.csv?s=FIG&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date  Open  High   Low  Close   Volume  Adj Close
0   2008-12-10  1.68  1.80  1.40   1.48   971700   1.063294
1   2008-12-09  1.98  1.99  1.61   1.70   430400   1.221351
2   2008-12-08  1.90  2.10  1.86   1.94   916600   1.393777
3   2008-12-05  1.97  1.97  1.66   1.76  1170200   1.264458
4   2008-12-04  1.73  1.95  1.60   1.89   694900   1.357855
5   2008-12-03  2.40  2.55  1.47   1.87  1623600   1.343486
6   2008-12-02  2.50  2.60  2.44   2.50   218700   1.796105
7   2008-12-01  2.90  3.00  2.23   2.50   245500   1.796105
8   2008-11-28  3.29  3.29  2.75   3.05   154600   2.191248
9   2008-11-26  2.41  3.04  2.38   3.02   558400   2.169694
10  2008-11-25  2.36  2.43  2.31   2.40   298500   1.724260
11  2008-11-24  2.21  2.56  2.09   2.41   498800   1.731445
12  2008-11-21  2.17  2.23  1.80   2.06  1048700   1.479990
http://chart.finance.yahoo.com/table.csv?s=BFED&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
         Date    Open    High   Low   Close  Volume  Adj Close
0  2008-12-09  8.0500  8.0500  8.05  8.0500     200     7.5153
1  2008-12-05  8.4000  8.4000  8.40  8.4000    1500     7.8421
2  2008-12-04  7.7500  8.4000  7.75  8.4000     500     7.8421
3  2008-12-03  7.7500  7.7500  7.75  7.7500    1500     7.2352
4  2008-12-02  8.1242  8.1242  8.08  8.0800    1500     7.5433
5  2008-12-01  8.4100  8.4100  8.40  8.4000     300     7.8421
6  2008-11-28  8.2500  8.7000  8.24  8.7000    4900     8.1221
7  2008-11-26  8.2400  8.2400  8.23  8.2300     300     7.6834
8  2008-11-24  7.9900  8.0250  7.99  7.9901     300     7.4594
9  2008-11-21  8.0800  8.0800  7.30  8.0700   11200     7.5340
http://chart.finance.yahoo.com/table.csv?s=BLK&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date        Open        High         Low       Close   Volume  \
0   2008-12-10  132.520004  135.360001  129.580002  132.720001   423000
1   2008-12-09  133.600006  137.289993  130.919998  133.119995   693000
2   2008-12-08  129.970001  138.770004  129.300003  138.130005   601900
3   2008-12-05  114.309998  128.529999  113.000000  128.309998   601300
4   2008-12-04  119.150002  122.900002  114.059998  115.739998   470600
5   2008-12-03  109.000000  121.849998  108.400002  121.800003   503900
6   2008-12-02  108.550003  113.559998  104.800003  113.360001   602400
7   2008-12-01  120.599998  121.489998  106.809998  107.059998   580900
8   2008-11-28  123.500000  125.750000  122.750000  125.709999   101000
9   2008-11-26  114.750000  125.610001  114.320000  124.730003   284400
10  2008-11-25  119.870003  120.889999  112.410004  117.430000   647600
11  2008-11-24  111.980003  117.449997  106.820000  116.129997   911700
12  2008-11-21  101.889999  109.260002   94.779999  108.900002  1007200

     Adj Close
0   108.600617
1   108.927920
2   113.027454
3   104.992049
4    94.706413
5    99.665125
6    92.758935
7    87.603840
8   102.226299
9   101.429375
10   95.493075
11   94.435924
12   88.556553
http://chart.finance.yahoo.com/table.csv?s=NDAQ&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close   Volume  Adj Close
0   2008-12-10  25.740000  26.420000  24.570000  25.400000  2521200  23.648158
1   2008-12-09  25.309999  27.660000  24.650000  25.410000  4511000  23.657469
2   2008-12-08  24.200001  26.000000  24.020000  25.469999  3484700  23.713330
3   2008-12-05  21.219999  23.350000  20.500000  23.350000  3257600  21.739547
4   2008-12-04  20.059999  23.190001  19.700001  21.740000  5505900  20.240589
5   2008-12-03  19.450001  20.950001  19.000000  20.450001  4363900  19.039561
6   2008-12-02  18.129999  20.090000  18.129999  20.020000  3669100  18.639218
7   2008-12-01  20.830000  21.000000  18.719999  18.799999  3652800  17.503361
8   2008-11-28  21.480000  21.600000  20.760000  21.500000  1401200  20.017142
9   2008-11-26  18.750000  21.760000  18.330000  21.559999  4082200  20.073003
10  2008-11-25  18.610001  19.709999  18.209999  19.120001  6563700  17.801292
11  2008-11-24  16.930000  19.100000  16.570000  18.870001  6188400  17.568534
12  2008-11-21  16.250000  16.920000  14.960000  16.840000  7189900  15.678543
http://chart.finance.yahoo.com/table.csv?s=BPOP&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date  Open  High   Low  Close  Volume  Adj Close
0   2008-12-10  5.72  5.93  5.65   5.93  145300  57.370663
1   2008-12-09  5.84  5.92  5.61   5.62  223400  53.597553
2   2008-12-08  5.94  6.02  5.86   5.95  157000  56.744740
3   2008-12-05  5.72  5.87  5.59   5.85  196500  55.791047
4   2008-12-04  6.06  6.27  5.82   5.87  102100  55.981786
5   2008-12-03  5.71  6.12  5.65   6.12  140200  58.366019
6   2008-12-02  5.74  5.92  5.37   5.91  126800  56.363261
7   2008-12-01  6.05  6.23  5.32   5.36  140300  51.117949
8   2008-11-28  6.05  6.25  6.05   6.25   66200  59.605819
9   2008-11-26  6.02  6.15  5.96   6.15  116800  58.652126
10  2008-11-25  6.15  6.18  5.94   6.09  162200  58.079912
11  2008-11-24  5.49  6.07  5.31   6.06  214100  57.793801
12  2008-11-21  6.05  6.05  5.25   5.76  281700  54.932721
http://chart.finance.yahoo.com/table.csv?s=C&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date  Open  High   Low  Close     Volume  Adj Close
0   2008-12-10  8.73  8.83  8.05   8.30   16340000  81.497036
1   2008-12-09  8.30  9.00  8.20   8.54   21702300  83.853579
2   2008-12-08  8.23  8.63  8.02   8.47   22910900  83.166250
3   2008-12-05  7.25  8.36  7.17   7.71   21521400  75.703872
4   2008-12-04  7.61  8.10  7.30   7.40   25963500  72.660008
5   2008-12-03  6.87  7.84  6.68   7.82   31407200  76.783952
6   2008-12-02  6.92  7.46  5.94   7.22   32692300  70.892600
7   2008-12-01  7.90  7.92  6.34   6.45   31481200  63.332034
8   2008-11-28  7.45  8.48  7.42   8.29   25077400  81.398849
9   2008-11-26  6.17  7.39  6.08   7.05   38172000  69.223386
10  2008-11-25  6.39  6.58  5.75   6.08   46312000  59.699033
11  2008-11-24  6.12  6.50  5.25   5.95   80378300  58.422574
12  2008-11-21  5.44  5.53  3.05   3.77  102772500  37.017329
http://chart.finance.yahoo.com/table.csv?s=NTRS&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close   Volume  Adj Close
0   2008-12-10  50.459999  51.349998  48.340000  50.270000  2213700  42.237466
1   2008-12-09  52.389999  52.790001  48.750000  50.110001  3180000  42.103032
2   2008-12-08  52.740002  52.980000  50.119999  52.860001  3049600  44.413616
3   2008-12-05  45.299999  50.580002  43.730000  50.580002  2723300  42.262673
4   2008-12-04  44.919998  48.939999  43.310001  46.169998  3506800  38.577846
5   2008-12-03  41.380001  45.610001  40.910000  45.549999  3088900  38.059799
6   2008-12-02  40.910000  42.830002  39.090000  42.619999  2869900  35.611605
7   2008-12-01  44.099998  44.709999  39.389999  39.400002  2980200  32.921101
8   2008-11-28  44.369999  46.110001  43.790001  45.889999  1666500  38.343890
9   2008-11-26  41.000000  44.430000  40.560001  44.410000  2382400  37.107260
10  2008-11-25  44.730000  45.000000  38.680000  41.560001  3654700  34.725913
11  2008-11-24  39.160000  44.070000  37.990002  43.889999  4563400  36.672768
12  2008-11-21  35.040001  38.169998  33.880001  37.939999  4200500  31.701180
http://chart.finance.yahoo.com/table.csv?s=EVR&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date   Open   High    Low  Close  Volume  Adj Close
0   2008-12-10  13.04  13.80  12.96  13.23  188800  10.933189
1   2008-12-09  12.78  14.32  12.70  13.08  452400  10.809230
2   2008-12-08  12.35  13.01  12.27  12.90  243000  10.660479
3   2008-12-05  11.34  12.42  11.07  12.00  164500   9.916725
4   2008-12-04  10.60  11.51  10.40  11.31   90100   9.346513
5   2008-12-03  10.55  10.90  10.11  10.84  117200   8.958108
6   2008-12-02  10.00  10.91   9.85  10.84  125800   8.958108
7   2008-12-01   9.76  10.12   9.71   9.96  277700   8.230882
8   2008-11-28  10.20  10.33   9.78  10.01   79200   8.272201
9   2008-11-26   8.20  10.39   8.20  10.33   76600   8.536647
10  2008-11-25   7.87   8.45   7.87   8.41   96500   6.949971
11  2008-11-24   7.39   8.09   7.17   7.69  116600   6.255800
12  2008-11-21   7.29   7.29   6.30   7.11  148700   5.783971
http://chart.finance.yahoo.com/table.csv?s=^SP500TR&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date         Open         High          Low        Close  Volume  \
0   2008-12-10  1444.000000  1444.000000  1444.000000  1444.000000       0
1   2008-12-09  1426.880005  1426.880005  1426.880005  1426.880005       0
2   2008-12-08  1460.599976  1460.599976  1460.599976  1460.599976       0
3   2008-12-05  1406.359985  1406.359985  1406.359985  1406.359985       0
4   2008-12-04  1356.810059  1356.810059  1356.810059  1356.810059       0
5   2008-12-03  1397.719971  1397.719971  1397.719971  1397.719971       0
6   2008-12-02  1361.790039  1361.790039  1361.790039  1361.790039       0
7   2008-12-01  1309.390015  1309.390015  1309.390015  1309.390015       0
8   2008-11-28  1437.680054  1437.680054  1437.680054  1437.680054       0
9   2008-11-26  1423.900024  1423.900024  1423.900024  1423.900024       0
10  2008-11-25  1374.790039  1374.790039  1374.790039  1374.790039       0
11  2008-11-24  1365.630005  1365.630005  1365.630005  1365.630005       0
12  2008-11-21  1282.589966  1282.589966  1282.589966  1282.589966       0

      Adj Close
0   1444.000000
1   1426.880005
2   1460.599976
3   1406.359985
4   1356.810059
5   1397.719971
6   1361.790039
7   1309.390015
8   1437.680054
9   1423.900024
10  1374.790039
11  1365.630005
12  1282.589966
http://chart.finance.yahoo.com/table.csv?s=GBL&a=10&b=21&c=2008&d=11&e=10&f=2008&g=d&ignore=.csv
          Date       Open       High        Low      Close  Volume  Adj Close
0   2008-12-10  26.870001  28.540000  26.210000  27.340001  103200  12.263661
1   2008-12-09  27.499999  28.490000  25.260000  26.719999  138300  11.985552
2   2008-12-08  27.499999  29.020001  26.540001  28.010001  117000  12.564197
3   2008-12-05  24.540000  27.200000  23.240000  26.810000  118800  12.025923
4   2008-12-04  25.750000  27.829999  25.050000  25.370000  105500  10.976292
5   2008-12-03  22.790001  26.190000  22.790001  26.049999  105700  11.270493
6   2008-12-02  23.469999  24.280000  22.490000  23.360001  216700  10.106669
7   2008-12-01  26.420000  26.990000  22.690001  22.840000  154500   9.881692
8   2008-11-28  26.890000  27.670000  26.360001  27.430000   27900  11.867548
9   2008-11-26  25.830000  27.389999  25.830000  27.389999  137000  11.850242
10  2008-11-25  28.000000  28.000000  24.809999  26.790000   99900  11.590653

,Date,Open,High,Low,Close,Volume,Adj Close,Date,Open,High,...,Close,Volume,Adj Close,Date,Open,High,Low,Close,Volume,Adj Close
0,2008-12-10,42.349998,43.590000,40.700001,41.759998,4085900,37.144048,2008-12-10,14.50,14.65,...,1444.000000,0,1444.000000,2008-12-10,26.870001,28.540000,26.210000,27.340001,103200,12.263661
1,2008-12-09,43.200001,45.650002,41.360001,41.799999,6530100,37.179628,2008-12-09,14.37,15.29,...,1426.880005,0,1426.880005,2008-12-09,27.499999,28.490000,25.260000,26.719999,138300,11.985552
2,2008-12-08,41.490002,44.419998,41.040001,43.869999,5589700,39.020820,2008-12-08,14.62,14.96,...,1460.599976,0,1460.599976,2008-12-08,27.499999,29.020001,26.540001,28.010001,117000,12.564197
3,2008-12-05,36.220001,40.389999,35.250000,40.279999,6371500,35.827641,2008-12-05,13.32,14.24,...,1406.359985,0,1406.359985,2008-12-05,24.540000,27.200000,23.240000,26.810000,118800,12.025923
4,2008-12-04,36.549999,40.389999,35.880001,37.320000,5448000,33.194826,2008-12-04,13.99,14.07,...,1356.810059,0,1356.810059,2008-12-04,25.750000,27.829999,25.050000,25.370000,105500,10.976292
5,2008-12-03,36.619999,36.930000,34.799999,36.599998,6007600,32.554410,2008-12-03,13.41,14.34,...,1397.719971,0,1397.719971,2008-12-03,22.790001,26.190000,22.790001,26.049999,105700,11.270493
6,2008-12-02,35.880001,37.259998,34.110001,36.930000,4675000,32.847935,2008-12-02,12.69,13.62,...,1361.790039,0,1361.790039,2008-12-02,23.469999,24.280000,22.490000,23.360001,216700,10.106669
7,2008-12-01,40.380001,41.000000,35.180000,35.430000,5858900,31.513738,2008-12-01,14.47,14.84,...,1309.390015,0,1309.390015,2008-12-01,26.420000,26.990000,22.690001,22.840000,154500,9.881692
8,2008-11-28,40.650002,42.500000,39.900002,42.110001,1833800,37.455363,2008-11-28,14.80,15.11,...,1437.680054,0,1437.680054,2008-11-28,26.890000,27.670000,26.360001,27.430000,27900,11.867548
9,2008-11-26,35.700001,40.799999,35.250000,40.650002,5778200,36.156745,2008-11-26,14.26,14.96,...,1423.900024,0,1423.900024,2008-11-26,25.830000,27.389999,25.830000,27.389999,137000,11.850242
10,2008-11-25,38.290001,38.740002,35.669998,37.750000,6608200,33.577296,2008-11-25,15.33,15.33,...,1374.790039,0,1374.790039,2008-11-25,28.000000,28.000000,24.809999,26.790000,99900,11.590653
11,2008-11-24,33.680000,36.900002,32.029999,36.090000,7017300,32.100785,2008-11-24,14.13,15.73,...,1365.630005,0,1365.630005,2008-11-24,26.990000,28.450001,25.530001,27.610000,161700,11.945425
12,2008-11-21,29.809999,32.080002,28.240000,31.780001,8064700,28.267192,2008-11-21,13.42,13.48,...,1282.589966,0,1282.589966,2008-11-21,23.400000,25.999999,22.500000,25.959998,219300,11.231554